### ISSUE TITLE
Ngebug Pas Kang Sticker Animated

### ISSUE THREAD

**Issue by sonzaiekkusu** [muhammadrizky16/Kyy-Userbot#10]
2022-02-18T03:05:32.308359+00:00 app[worker.1]: 2022-02-18 03:05:32,308 - userbot - ERROR - An invalid Peer was used. Make sure to pass the right peer type and that the value is valid (for instance, bots cannot start conversations) (caused by SendMediaRequest)
2022-02-18T03:05:34.358090+00:00 app[worker.1]: 2022-02-18 03:05:34,357 - telethon.client.updates - ERROR - Unhandled exception on kang
2022-02-18T03:05:34.358100+00:00 app[worker.1]: Traceback (most recent call last):
2022-02-18T03:05:34.358101+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/client/updates.py", line 467, in _dispatch_update
2022-02-18T03:05:34.358102+00:00 app[worker.1]:     await callback(event)
2022-02-18T03:05:34.358102+00:00 app[worker.1]:   File "/root/userbot/userbot/modules/stickers.py", line 48, in kang
2022-02-18T03:05:34.358102+00:00 app[worker.1]:     elif "image" in message.media.document.mime_type.split("/"):
2022-02-18T03:05:34.358103+00:00 app[worker.1]: AttributeError: 'MessageMediaUnsupported' object has no attribute 'document'

**Comment by muhammadrizky16** [comment]
belum support kang sticker vid bwang

**Comment by sonzaiekkusu** [comment]
> belum support kang sticker vid bwang

ditunggu yaak

**Comment by muhammadrizky16** [comment]
iyaa bwang
